name: event_api
description: Holds APIRepository, which is primarily used for making requests to a server
version: 0.3.0
repository: https://github.com/VHCBlade/event_api

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  event_authentication: ^0.1.3+1
  event_bloc: ^4.2.0
  event_db: ^0.2.0

  http: ^1.0.0
  tuple: ^2.0.0

dev_dependencies:
  event_bloc_tester: ^0.1.4

  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.0.0
